package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/unknown-prince/user-dashboard/graph/model"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	var users []*model.User
	dummyUser := model.User{
		Name:       "John",
		Surname:    "Doe",
		Number:     123,
		Gender:     "Male",
		Country:    "South Africa",
		Dependents: 3,
		Birthdate:  "22-Jun-1995",
	}
	users = append(users, &dummyUser)
	return users, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
