// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type User struct {
	ID         int    `json:"id"`
	Name       string `json:"name"`
	Surname    string `json:"surname"`
	Number     int    `json:"number"`
	Gender     string `json:"gender"`
	Country    string `json:"country"`
	Dependents int    `json:"dependents"`
	Birthdate  string `json:"birthdate"`
}
